// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using portfolio.DataAccess.Data;

#nullable disable

namespace portfolio.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240425131832_SeedSkillsTable")]
    partial class SeedSkillsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("portfolio.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "images/csharp.png",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "images/csharp.png",
                            Name = "C#2"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "images/csharp.png",
                            Name = "C#3"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "images/csharp.png",
                            Name = "C#4"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "images/csharp.png",
                            Name = "C#5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
